version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    env_file:
      - .env.example

  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - backend_network
    env_file:
      - .env.example
    volumes:
      - ./alembic:/app/alembic
      - .:/app

volumes:
  postgres_data:

networks:
  backend_network:
